- name: Setup CloudWatch Agent on RHEL 9 EC2 for memory utilization
  hosts: local
  connection: local
  become: true
  vars:
    cw_agent_config_path: /opt/aws/amazon-cloudwatch-agent/bin/config.json
    cw_agent_rpm_url: https://s3.amazonaws.com/amazoncloudwatch-agent/redhat/amd64/latest/amazon-cloudwatch-agent.rpm

  tasks:

    - name: Ensure required directories exist
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /opt/aws/amazon-cloudwatch-agent
        - /opt/aws/amazon-cloudwatch-agent/bin

    - name: Download CloudWatch Agent RPM for RHEL
      get_url:
        url: "{{ cw_agent_rpm_url }}"
        dest: /tmp/amazon-cloudwatch-agent.rpm
        mode: '0644'

    - name: Install CloudWatch Agent using dnf (skip GPG check)
      dnf:
        name: /tmp/amazon-cloudwatch-agent.rpm
        state: present
        disable_gpg_check: true

    - name: Upload CloudWatch Agent config for memory usage
      copy:
        dest: "{{ cw_agent_config_path }}"
        content: |
          {
            "metrics": {
              "append_dimensions": {
                "InstanceId": "${aws:InstanceId}"
              },
              "metrics_collected": {
                "mem": {
                  "measurement": [
                    "mem_used_percent"
                  ],
                  "metrics_collection_interval": 60
                }
              }
            }
          }
        mode: '0644'

    - name: Start CloudWatch Agent with memory config
      command: >
        /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl
        -a fetch-config
        -m ec2
        -c file:{{ cw_agent_config_path }}
        -s
