- name: Setup CloudWatch Agent for memory utilization
  hosts: local
  connection: local
  become: true
  tasks:

    - name: Install CloudWatch Agent (Amazon Linux / RHEL)
      yum:
        name: amazon-cloudwatch-agent
        state: present

    - name: Create CloudWatch Agent config directory
      file:
        path: /opt/aws/amazon-cloudwatch-agent/bin
        state: directory
        mode: '0755'

    - name: Upload CloudWatch Agent config file
      copy:
        dest: /opt/aws/amazon-cloudwatch-agent/bin/config.json
        content: |
          {
            "metrics": {
              "append_dimensions": {
                "InstanceId": "${aws:InstanceId}"
              },
              "metrics_collected": {
                "mem": {
                  "measurement": [
                    "mem_used_percent"
                  ],
                  "metrics_collection_interval": 60
                }
              }
            }
          }
        mode: '0644'

    - name: Start CloudWatch Agent with config
      command: >
        /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl
        -a fetch-config
        -m ec2
        -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json
        -s
