- name: Ansible conditions
  hosts: local
  connection: local
  vars:
    NUMBER: 78
  tasks:
  - name: Print the number if the number is lessthan or equal to 100
    ansible.builtin.debug:
      msg: "Given number {{ NUMBER }} is lessthan or equal to 100"
    when: NUMBER < 100

  - name: Print the number if it greater than 100
    ansible.builtin.debug:
      msg: "Given number {{ NUMBER }} is greater than 100"
    when: NUMBER > 100