- name: install packages using loops
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: installed
    loop:
    - mysql
    - zip
    - httpd




